[build]
  publish = "frontend"
  command = "echo 'Building frontend for Netlify'"

[[redirects]]
  from = "/api/*"
  to = "https://todo-list-fullstack-1l3f.onrender.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200