[build]
  publish = "frontend"
  command = "echo 'Building frontend for Netlify'"

[[redirects]]
  from = "/api/*"
  to = "https://tu-backend-en-render.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200